### ISSUE TITLE
Caching/Reuse ViewControllers

### ISSUE THREAD

**Issue by manumax** [levigroker/GRKContainerViewController#2]
Hi,
  I'm using your lib in a project of mine, and I would say that it is quite nice and very useful. Using it, though, I ran into a quite common problem related with the reuse of the view controllers. As far as I understand, at the moment, the only way to cache and reuse a view controller to be used with your lib is to demand this caching stuff somewhere outside the lib itself. Since it is a common recurring pattern (unless your using a completely different view controller every time), it is pretty annoying to have to rewrite such code.

  So, I was wondering if it makes sense to add this caching capability to you lib. What I expect is to have a some sort of registerClass/registerNib and dequeueViewController similar to what happens with UITableView and UICollectionView.

  Just to clarify, I would expect something like this:
```objective-c
GRKContainerViewController *container = ...;
[container registerClass:[SomeClass class] forReuseIdentifier:@"Identifier"]
```
and in `setViewController:animated:completion:` if needed:
```objective-c
UIViewController *controllerToPresent = [container dequeueReusableViewControllerWithReuseIdentifier:@"Identifier"];
```
What do you think? I really hope I explained myself and it makes sense in some way :)

**Comment by levigroker** [comment]
Hi Manuele,

Thanks for the feedback!

I appreciate what you are suggesting, and this was not an oversight in design. The use case for the original design is evident in the sample application, that of an embedded view controller within another view controller. Rather than add the complexity of a mechanism as you suggest, the "parent" view controller is intended to create (with whatever state is needed) the view controllers and cache (as it sees fit) them.

As it is currently, it is trivial for the "parent" view controller to instantiate a new view controller, or use an instance from a cache.

Of course, you are welcome to disagree, so feel free to fork and add the functionality you are interested in.

Cheers,

Levi
